services:
  mongodb:
    image: mongo
    container_name: mongo-db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: aituuser
      MONGO_INITDB_ROOT_PASSWORD: aitupass
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: aituuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: aitupass
      ME_CONFIG_MONGODB_URL: mongodb://aituuser:aitupass@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  redis:
    image: redis
    ports:
      - '6379:6379'
volumes:
  mongo_data: