version: '3.7'

services:
  postgres:
    image: postgres:17
    container_name: aitu-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: aitudb
      POSTGRES_USER: aituuser
      POSTGRES_PASSWORD: aitupass
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
    driver: local