services:
  redis:
    networks:
      - aitu-net
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  mongodb:
    networks:
      - aitu-net
    image: mongo
    container_name: mongo-db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: aituuser
      MONGO_INITDB_ROOT_PASSWORD: aitupass
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  mongo_data:
  redis_data:

networks:
  aitu-net:
    driver: bridge
    name: aitu-net