server:
  port: 8080
  error:
    include-message: always
secure-talk:
  domain: ${SECURE_TALK_DOMAIN:https://aitunet.kz/api}
  file-download-path: ${secure-talk.domain}/v1/file/
  mail-confirmation: ${MAIL_CONFIRMATION_ENABLED:true}
  chat:
    user-destination: ${USER_WS_DESTINATION:/queue/messages}
spring:
  data:
    mongodb:
      auto-index-creation: true
      database: secureTalk
      uri: mongodb://aituuser:aitupass@mongo-db:27017/aitunetwork?authSource=admin
  profiles:
    active: local
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "reluckytryhrd@gmail.com"
    password: ${MAIL_PASS:xxxxxxxxxxx}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
logging:
  level:
    org.springframework.security: info
token:
  key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
