server:
  port: 8080
secure-talk:
  domain: ${SECURE_TALK_DOMAIN:https://aitunet.kz/api}
  file-download-path: ${secure-talk.domain}/v1/file/
spring:
  data:
    mongodb:
      auto-index-creation: true
      database: secureTalk
      uri: mongodb://aituuser:aitupass@mongo-db:27017/aitunetwork?authSource=admin
  profiles:
    active: local
logging:
  level:
    org.springframework.security: info
    org.springframework.data.mongodb.core: debug
token:
  key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
