server:
  port: 8080

secure-talk:
  domain: ${SECURE_TALK_DOMAIN:http://localhost:${server.port}}
spring:
  data:
    mongodb:
      auto-index-creation: true
      database: secureTalk
      uri: mongodb://aituuser:aitupass@host.docker.internal:27017/aitunetwork?authSource=admin
logging:
  level:
    org.springframework.security: trace
    org.springframework.data.mongodb.core: debug
token:
  key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
