server:
  port: 8080

logging:
  level:
    org.springframework.security: debug
spring:
  data:
    mongodb:
      uri: mongodb://aituuser:aitupass@localhost:27017/aitunetwork?authSource=admin
    redis:
      host: localhost
      port: 6379