name: CI/CD Pipeline for Aitu Network Backend Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Installation of Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Maven caching of dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Running of tests
        run: mvn test

      - name: Building of project
        run: mvn clean package -DskipTests

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Логин в Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Сборка и пуш Docker-образа
        run: |
          docker build -t aitu-network:latest .
          docker tag myapp:latest reluckyyy/aitu-network:latest
          docker push reluckyyy/aitu-network:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: connect to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull reluckyyy/aitu-network:latest
            docker stop aitu-network || true
            docker rm myapp || true
            docker run -d --name aitu-network -p 8080:8080 reluckyyy/myapp:latest